# Generated by Django 3.1.13 on 2021-12-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TTDK', 'Ttadak Bot')], max_length=4)),
                ('type', models.CharField(choices=[('AUTO', 'Automated Bot'), ('MANU', 'Manual Bot'), ('INDI', 'Indicator Bot')], default='AUTO', max_length=4)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('default_setting', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SubscribedBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTV', 'Active'), ('INAC', 'Inactive')], default='INAC', max_length=4)),
                ('run_type', models.CharField(choices=[('BACK', 'Back-testing Mode'), ('SIML', 'Simulation Mode'), ('DRYR', 'Dry-run Mode'), ('LIVR', 'Live-run Mode')], default='LIVR', max_length=4)),
                ('user_bot_settings', models.JSONField(blank=True, default=dict, null=True)),
                ('subscribe_start_date', models.DateTimeField(null=True)),
                ('subscribe_end_date', models.DateTimeField(null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bots.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
