# Generated by Django 3.1.13 on 2022-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20211230_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(choices=[('TTDK', 'Ttadak Bot'), ('NTRK', 'News Tracker')], max_length=4),
        ),
        migrations.AlterField(
            model_name='subscribedbot',
            name='subscribe_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
