# Generated by Django 3.1.13 on 2022-02-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20220207_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinnessNewsData',
        ),
    ]
