version: "3"

networks:
  collector-network:
    driver: bridge

services:
  collector-rmqserver:
    image: rabbitmq:3.9-management
    container_name: collector-rmqserver
    networks:
      - collector-network

  collector-producer-BTC_USDT: &collector-base
    build:
      context: .
      dockerfile: compose/local/collector/Dockerfile
      args:
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    image: ld_platform_local_collector
    container_name: collector-producer-BTC_USDT
    env_file:
      - ./.envs/.local/.collector
    depends_on:
      - collector-rmqserver
    networks:
      - collector-network
    restart: always
    command: /start-producer BTC_USDT

  collector-producer-ETH_USDT:
    <<: *collector-base
    container_name: collector-producer-ETH_USDT
    command: /start-producer ETH_USDT

  collector-producer-XRP_USDT:
    <<: *collector-base
    container_name: collector-producer-XRP_USDT
    command: /start-producer XRP_USDT

  collector-producer-BNB_USDT:
    <<: *collector-base
    container_name: collector-producer-BNB_USDT
    command: /start-producer BNB_USDT

  collector-producer-BCH_USDT:
    <<: *collector-base
    container_name: collector-producer-BCH_USDT
    command: /start-producer BCH_USDT

  collector-consumer:
    <<: *collector-base
    container_name: collector-consumer
    env_file:
      - ./.envs/.local/.aws
      - ./.envs/.local/.collector
    command: /start-consumer

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - collector-network
