version: "3"

services:
  docs:
    image: ld_platform_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./backend/config:/app/backend/config:z
      - ./backend/ld_platform:/app/backend/ld_platform:z
    ports:
      - "7000:7000"
    command: /start-docs
