version: "3"

volumes:
  production_postgres_data: {}
  django_static_volume: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    image: ld_platform_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: ld_platform_production_postgres
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: ld_platform_production_nginx
    container_name: nginx
    volumes:
      - ./compose/production/nginx/conf:/etc/nginx/conf
      - ./compose/production/nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static_volume:/app/backend/django_static
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: ld_platform_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ld_platform_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: ld_platform_production_flower
    command: /start-flower
