version: "3"

volumes:
  local_postgres_data: {}
  django_static_volume: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ld_platform_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - django_static_volume:/app/backend/django_static
    env_file:
      - ./.envs/.local/.aws
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "5000:5000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: ld_platform_local_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    <<: *django
    image: ld_platform_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ld_platform_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: ld_platform_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower

  react:
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    image: ld_platform_local_react
    container_name: react
    volumes:
      - ./frontend:/app/frontend
    env_file:
      - ./frontend/.env.development
    ports:
      - "9000:9000"

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    image: ld_platform_local_nginx
    container_name: nginx
    volumes: # uses /compose/local
      - ./compose/local/nginx/conf:/etc/nginx/conf
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - django_static_volume:/app/backend/django_static
    depends_on:
      - django
      - react
    ports:
      - "80:80"
      - "443:443"

  selenium-chrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    ports:
      - "4444:4444"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    depends_on:
      - django
      - react
    ports:
      - "1025:1025"
      - "8025:8025"
    env_file:
      - ./.envs/.local/.mailhog
