version: "3"

volumes:
  production_postgres_data: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
    image: ld_platform_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ld_platform_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: ld_platform_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ld_platform_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: ld_platform_production_flower
    command: /start-flower
