# Generated by Django 3.1.13 on 2021-12-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexchangesetting',
            old_name='name',
            new_name='exchange_name',
        ),
    ]
