# Generated by Django 3.1.13 on 2021-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211208_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangesetting',
            name='exchange_name',
            field=models.CharField(choices=[('binance', 'Binance'), ('upbit', 'Upbit')], max_length=32),
        ),
    ]
