# Generated by Django 3.1.13 on 2021-12-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20211201_1557'),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='default_setting',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bot',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funds.fund'),
        ),
        migrations.AddField(
            model_name='bot',
            name='type',
            field=models.CharField(choices=[('AUTO', 'Automated Bot'), ('MANU', 'Manual Bot'), ('INDI', 'Indicator Bot')], default='AUTO', max_length=4),
        ),
        migrations.AddField(
            model_name='bot',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
