# Generated by Django 3.1.13 on 2021-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20211201_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(choices=[('TTDK', 'Ttadak Bot')], max_length=4),
        ),
    ]
