# Generated by Django 3.1.13 on 2021-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20211205_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='default_setting',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
