# Generated by Django 3.1.13 on 2021-12-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(choices=[('TTDK', 'Ttadak Bot'), ('NTSM', 'News Tracker Summary'), ('NTKW', 'News Tracker Summary'), ('NTSR', 'News Tracker Summary')], max_length=4),
        ),
    ]
