# Generated by Django 3.1.13 on 2021-12-08 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0002_auto_20211205_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscribedBot',
            new_name='SubscribedBot',
        ),
    ]
