# Generated by Django 3.1.13 on 2021-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20211208_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedbot',
            name='user_bot_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
