# Generated by Django 3.1.13 on 2022-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211230_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangesetting',
            name='exchange_name',
            field=models.CharField(choices=[('binance', 'Binance'), ('upbit', 'Upbit'), ('bybit', 'Bybit')], max_length=32),
        ),
    ]
